const STUDENTS={amir:{name:'Амир',pin:'2468'},samir:{name:'Самир',pin:'1357'}};
const SUBJECTS={mathematics:'Математика',russian:'Русский язык',english:'Английский язык',informatics:'Информатика'};
const SUBJECT_ORDER=['mathematics','russian','english','informatics'];
const LESSONS_PER_SUBJECT=100;

// Курс построен как 100 уроков по каждому предмету. Темы идут последовательно,
// а после ошибок конкретная тема автоматически получает дополнительные задания.
const CURRICULUM={
 mathematics:['Натуральные числа и действия','Делимость чисел','Признаки делимости','НОД и НОК','Обыкновенные дроби','Сравнение дробей','Сложение и вычитание дробей','Умножение дробей','Деление дробей','Смешанные числа','Десятичные дроби','Действия с десятичными дробями','Округление чисел','Отношения','Пропорции','Проценты','Нахождение процентов от числа','Нахождение числа по процентам','Задачи на проценты','Положительные и отрицательные числа','Координатная прямая','Сравнение рациональных чисел','Модуль числа','Сложение рациональных чисел','Вычитание рациональных чисел','Умножение рациональных чисел','Деление рациональных чисел','Буквенные выражения','Раскрытие скобок','Подобные слагаемые','Уравнения','Линейные уравнения','Задачи с помощью уравнений','Координатная плоскость','Зависимости и графики','Среднее арифметическое','Средняя скорость','Масштаб','Окружность и круг','Длина окружности и площадь круга','Углы','Перпендикулярные прямые','Параллельные прямые','Треугольники','Четырёхугольники','Прямоугольник и квадрат','Площадь фигур','Объём и площадь поверхности','Комбинаторика','Логические задачи','Олимпиадные задачи'],
 russian:['Текст и его признаки','Типы речи','Стили речи','Лексическое значение слова','Однозначные и многозначные слова','Синонимы','Антонимы','Омонимы','Фразеологизмы','Заимствованные слова','Неологизмы и устаревшие слова','Морфемика','Состав слова','Чередование гласных','Правописание приставок','Буквы з/с на конце приставок','Правописание корней','Безударные гласные','Согласные в корне','Имя существительное','Одушевлённость и род существительных','Склонение существительных','Падежи','Правописание НЕ с существительными','Имя прилагательное','Степени сравнения','Разряды прилагательных','Имя числительное','Количественные числительные','Порядковые числительные','Местоимение','Глагол','Виды глагола','Спряжение глаголов','Время и лицо глагола','НЕ с глаголами','Причастие: знакомство','Деепричастие: знакомство','Наречие','Служебные части речи','Предлог','Союз','Частица','Междометие','Словосочетание','Грамматическая основа','Простое предложение','Однородные члены','Обращение','Сложное предложение','Пунктуация','Повторение и олимпиадная грамотность'],
 english:['Present Simple','Present Continuous','Past Simple','Future: be going to','Future: will','There is/There are','Countable and uncountable nouns','Some/any/much/many','Articles a/an/the','Plural nouns','Possessive case','Personal pronouns','Object pronouns','Adjectives','Adverbs of frequency','Prepositions of time','Prepositions of place','Question words','Yes/No questions','Wh-questions','Short answers','Can/can’t','Must/mustn’t','Have to','Should/shouldn’t','Comparatives','Superlatives','Past time expressions','Irregular verbs','Present vs Past','Present Simple vs Continuous','Future forms review','Vocabulary: school','Vocabulary: family','Vocabulary: hobbies','Vocabulary: food','Vocabulary: travel','Vocabulary: weather','Vocabulary: technology','Reading comprehension','Listening strategies','Writing a message','Writing a description','Speaking: introducing yourself','Speaking: daily routine','Speaking: opinions','Grammar mixed practice','Vocabulary mixed practice','Olympiad English','Final review','Final diagnostic'],
 informatics:['Computer devices','Input and output devices','Operating systems','Files and folders','File extensions','Information and data','Units of information','Binary representation','Encoding information','Computer networks','Internet basics','Browser and search','Digital safety','Strong passwords','Copyright and plagiarism','Algorithms','Algorithm properties','Flowcharts','Linear algorithms','Branching','Loops','Variables','Expressions','Logical operations','Truth tables','Scratch basics','Sprites and events','Coordinates in Scratch','Conditions in Scratch','Loops in Scratch','Variables in Scratch','Lists in Scratch','Debugging','Python basics','Python output','Python variables','Python input','Python arithmetic','Python conditions','Python loops','Python strings','Python lists','Functions','Algorithms with numbers','Algorithms with text','Spreadsheets','Cells and formulas','Charts','Information models','Robotics basics','Final project and review']
};

const BASE_BANK=[
{id:'m1',subject:'mathematics',topic:'Десятичные дроби',text:'Вычисли: 4,8 · 0,5',answer:'2.4',hint:'При умножении на 0,5 можно рассуждать как о делении числа на 2.'},
{id:'m2',subject:'mathematics',topic:'Средняя скорость',text:'Машина проехала 120 км за 3 часа. Какова средняя скорость?',answer:'40',hint:'Используй формулу: скорость = расстояние ÷ время.'},
{id:'m3',subject:'mathematics',topic:'Прямоугольник и квадрат',text:'Длина прямоугольника 14 см, ширина на 5 см меньше. Найди периметр и площадь. Запиши через ;',answer:'46;126',hint:'Сначала найди ширину. Затем примени формулы периметра и площади.'},
{id:'m4',subject:'mathematics',topic:'Проценты',text:'Найди 30% от 50.',answer:'15',hint:'10% от числа — это одна десятая. Подумай, сколько таких частей составляет 30%.'},
{id:'m5',subject:'mathematics',topic:'Уравнения',text:'Реши: 3x + 7 = 31. Запиши значение x.',answer:'8',hint:'Сначала убери 7, затем раздели на коэффициент при x.'},
{id:'m6',subject:'mathematics',topic:'Последовательности',text:'Продолжи: 3, 7, 13, 21, 31, …',answer:'43',hint:'Посмотри на разности соседних чисел: они увеличиваются на 2.'},
{id:'m7',subject:'mathematics',topic:'Делимость чисел',text:'Вычисли: 36 : 2',answer:'18',hint:'Раздели 36 на 2. Проверь результат обратным умножением.'},
{id:'m8',subject:'mathematics',topic:'Обыкновенные дроби',text:'Вычисли: 2/3 + 5/8. Запиши неправильной дробью.',answer:'31/24',hint:'Приведи дроби к общему знаменателю, затем сложи числители.'},
{id:'m9',subject:'mathematics',topic:'Десятичные дроби',text:'Вычисли: 1,5 · 0,4',answer:'0.6',hint:'Перемножь числа без запятых, затем верни нужное количество знаков.'},
{id:'m10',subject:'mathematics',topic:'Проценты',text:'Найди 25% от 80.',answer:'20',hint:'25% — это четверть числа.'},
{id:'m11',subject:'mathematics',topic:'Линейные уравнения',text:'Реши: 4x − 9 = 27. Запиши x.',answer:'9',hint:'Сначала прибавь 9 к обеим частям, затем раздели на 4.'},
{id:'m12',subject:'mathematics',topic:'Комбинаторика',text:'У Пети 3 красных, 4 синих и 2 зелёных карандаша. Сколько карандашей всего?',answer:'9',hint:'Сложи количества всех трёх цветов.'},
{id:'m13',subject:'mathematics',topic:'Делители числа',text:'У числа 18 есть делители 1, 2, 3, 6, 9, 18. Сколько их всего?',answer:'6',hint:'Пересчитай все положительные делители 18.'},
{id:'m14',subject:'mathematics',topic:'Площадь фигур',text:'Прямоугольник имеет длину 12 см и ширину 7 см. Найди площадь.',answer:'84',hint:'Площадь прямоугольника равна длина × ширина.'},
{id:'m15',subject:'mathematics',topic:'Сравнение дробей',text:'Какая дробь больше: 3/4 или 2/3? Напиши только большую дробь.',answer:'3/4',hint:'Приведи дроби к общему знаменателю или сравни их десятичные значения.'},
{id:'m16',subject:'mathematics',topic:'Последовательности',text:'Продолжи: 2, 5, 10, 17, 26, …',answer:'37',hint:'Разности соседних чисел увеличиваются на 2.'},
{id:'r1',subject:'russian',topic:'Части речи',text:'Определи часть речи слова «быстро» в предложении: «Мальчик быстро бежал».',answer:'наречие',hint:'Слово обозначает признак действия и отвечает на вопрос «как?».'},
{id:'r2',subject:'russian',topic:'Орфография',text:'Выбери вариант: «неправда» или «не правда» в предложении «Это ___, а выдумка».',answer:'неправда',hint:'Проверь, есть ли противопоставление с союзом «а».'},
{id:'r3',subject:'russian',topic:'Синтаксис',text:'Сколько грамматических основ в предложении: «Солнце взошло, и птицы запели»?',answer:'2',hint:'Найди пары подлежащее + сказуемое.'},
{id:'r4',subject:'russian',topic:'Пунктуация',text:'Нужна ли запятая: «Когда стемнело мы пошли домой»? Ответ: да или нет.',answer:'да',hint:'Придаточная часть начинается с «когда» и отделяется запятой.'},
{id:'r5',subject:'russian',topic:'Морфемика',text:'Сколько корней в слове «лесоруб»?',answer:'2',hint:'Найди части слова, связанные с двумя самостоятельными словами.'},
{id:'r6',subject:'russian',topic:'Орфография',text:'Выбери правильное написание: «безвкусный» или «безвкустный».',answer:'безвкусный',hint:'Разбери слово по составу и обрати внимание на корень «вкус».'},
{id:'r7',subject:'russian',topic:'Синтаксис',text:'Какой знак нужен: «Я знаю ___ ты придёшь»? Напиши слово «запятая».',answer:'запятая',hint:'Части сложноподчинённого предложения разделяются запятой.'},
{id:'r8',subject:'russian',topic:'Части речи',text:'Определи часть речи слова «три» в сочетании «три книги».',answer:'числительное',hint:'Слово обозначает количество и отвечает на вопрос «сколько?».'},
{id:'e1',subject:'english',topic:'Present Simple',text:'Choose: He ___ football every Sunday. (play / plays)',answer:'plays',hint:'С he/she/it в Present Simple обычно добавляется -s.'},
{id:'e2',subject:'english',topic:'Past Simple',text:'Choose: Yesterday I ___ to school. (go / went)',answer:'went',hint:'Yesterday указывает на прошлое; вспомни вторую форму go.'},
{id:'e3',subject:'english',topic:'Questions',text:'Make a question: You like pizza. Start with “Do”.',answer:'do you like pizza',hint:'Present Simple: Do + subject + verb.'},
{id:'e4',subject:'english',topic:'There is/There are',text:'Choose: ___ two books on the table. (There is / There are)',answer:'there are',hint:'После конструкции стоит существительное во множественном числе.'},
{id:'e5',subject:'english',topic:'Vocabulary: school',text:'Translate into English: «школа».',answer:'school',hint:'Вспомни базовое слово для места, где учатся дети.'},
{id:'e6',subject:'english',topic:'Present Simple',text:'Choose: I ___ TV every evening. (watch / watches)',answer:'watch',hint:'С I глагол в Present Simple не получает -s.'},
{id:'e7',subject:'english',topic:'Past Simple',text:'Choose: She ___ a book yesterday. (read / reads)',answer:'read',hint:'Yesterday требует прошедшего времени.'},
{id:'e8',subject:'english',topic:'There is/There are',text:'Choose: ___ a cat under the table. (There is / There are)',answer:'there is',hint:'После конструкции стоит один предмет.'},
{id:'i1',subject:'informatics',topic:'Алгоритмы',text:'Алгоритм: взять число 6, прибавить 4, умножить на 2. Какой результат?',answer:'20',hint:'Выполни действия строго по порядку.'},
{id:'i2',subject:'informatics',topic:'Units of information',text:'Сколько битов в одном байте?',answer:'8',hint:'Вспомни базовую единицу объёма информации.'},
{id:'i3',subject:'informatics',topic:'Логические операции',text:'Истинно или ложно: если A истинно и B истинно, то A И B истинно?',answer:'истинно',hint:'Операция И истинна только когда оба условия истинны.'},
{id:'i4',subject:'informatics',topic:'Binary representation',text:'Сколько цифр используется в двоичной системе счисления?',answer:'2',hint:'Вспомни, какие две цифры используют компьютеры в двоичном коде.'},
{id:'i5',subject:'informatics',topic:'Information and data',text:'Файл 20 МБ. После удаления 5 МБ сколько осталось?',answer:'15',hint:'Из общего объёма вычти удалённый объём.'},
{id:'i6',subject:'informatics',topic:'Алгоритмы',text:'Что выполнится раньше, если команда «вывести 5» записана выше команды «прибавить 2»?',answer:'вывести 5',hint:'Команды алгоритма выполняются по порядку записи.'},
{id:'i7',subject:'informatics',topic:'Логические операции',text:'Истинно или ложно: A ИЛИ B ложно, если A ложно и B ложно?',answer:'истинно',hint:'ИЛИ ложно только тогда, когда оба условия ложны.'},
{id:'i8',subject:'informatics',topic:'Computer networks',text:'Как называется программа для просмотра сайтов?',answer:'браузер',hint:'Например, Chrome — это ...'},
];

let current=null,state=null,todayTasks=[],lessonPlan=null,lessonFinished=false;
const key=id=>`tutor_state_v3_${id}`;
function freshState(id){return{student:id,completed:{mathematics:0,russian:0,english:0,informatics:0},attempts:[],scores:[],errors:[],strengths:[],lessons:0,lastLesson:null,streak:0,completedDates:[],courseStarted:false}}
function load(id){try{return JSON.parse(localStorage.getItem(key(id)))||freshState(id)}catch{return freshState(id)}}
function save(){localStorage.setItem(key(current),JSON.stringify(state))}
function selectStudent(id){document.getElementById('pinBox').hidden=false;document.getElementById('pin').value='';current=id;document.getElementById('selectedName').textContent=STUDENTS[id].name;document.getElementById('loginError').textContent=''}
function login(){const pin=document.getElementById('pin').value.trim();if(!current||pin!==STUDENTS[current].pin){document.getElementById('loginError').textContent='Неверный PIN.';return}state=load(current);sessionStorage.setItem('tutor_session',current);showDashboard()}
function logout(){sessionStorage.removeItem('tutor_session');current=null;state=null;document.getElementById('dashboard').hidden=true;document.getElementById('lesson').hidden=true;document.getElementById('login').hidden=false;document.getElementById('pinBox').hidden=true}
function dateKey(d=new Date()){return d.toISOString().slice(0,10)}
function topicStats(){const stats={};state.attempts.forEach(a=>{const k=a.subject+'|'+a.topic;if(!stats[k])stats[k]={subject:a.subject,topic:a.topic,n:0,ok:0};stats[k].n++;if(a.ok)stats[k].ok++});return stats}
function weakTopics(subject){return Object.values(topicStats()).filter(x=>(!subject||x.subject===subject)&&x.n>0).sort((a,b)=>(a.ok/a.n)-(b.ok/b.n)||a.ok-b.ok)}
function courseTopic(subject,lessonNo){const arr=CURRICULUM[subject];return arr[(lessonNo-1)%arr.length]}
function subjectProgress(subject){return Math.min(100,Math.round((state.completed[subject]||0)/LESSONS_PER_SUBJECT*100))}
function normalize(s){return String(s).trim().replace(/ё/g,'е').replace(/,/g,'.').replace(/[;]+$/,'').replace(/\s+/g,' ').toLowerCase()}
function genericTask(subject,topic,idx){
 const n=idx+1;
 if(subject==='mathematics'){
  const templates={
   'Натуральные числа и действия':()=>({text:`Вычисли: ${n+8} · 3 − ${n+2}`,answer:String((n+8)*3-(n+2)),hint:'Сначала выполни умножение, затем вычитание.'}),
   'Делимость чисел':()=>({text:`Делится ли ${12+n} на 3? Ответ: да или нет.`,answer:(12+n)%3===0?'да':'нет',hint:'Проверь делимость на 3 по сумме цифр.'}),
   'Признаки делимости':()=>({text:`Делится ли ${20+n} на 2? Ответ: да или нет.`,answer:(20+n)%2===0?'да':'нет',hint:'Число делится на 2, если последняя цифра чётная.'}),
   'НОД и НОК':()=>({text:'Найди НОД чисел 18 и 24.',answer:'6',hint:'Разложи числа на множители или перечисли общие делители.'}),
   'Обыкновенные дроби':()=>({text:'Сравни 5/8 и 3/4. Напиши большую дробь.',answer:'3/4',hint:'Приведи дроби к общему знаменателю.'}),
   'Сложение и вычитание дробей':()=>({text:'Вычисли: 1/2 + 1/4.',answer:'3/4',hint:'Приведи дроби к общему знаменателю.'}),
   'Умножение дробей':()=>({text:'Вычисли: 2/3 · 3/4.',answer:'1/2',hint:'Перемножь числители и знаменатели, затем сократи.'}),
   'Деление дробей':()=>({text:'Вычисли: 3/4 : 1/2.',answer:'3/2',hint:'При делении на дробь умножай на обратную дробь.'}),
   'Смешанные числа':()=>({text:'Представь 7/3 смешанным числом.',answer:'2 1/3',hint:'Раздели числитель на знаменатель и выдели целую часть.'}),
   'Округление чисел':()=>({text:'Округли 7,46 до десятых.',answer:'7.5',hint:'Посмотри на цифру сотых.'}),
   'Отношения':()=>({text:'Сократи отношение 12:8.',answer:'3:2',hint:'Раздели оба числа на их общий делитель.'}),
   'Пропорции':()=>({text:'Реши пропорцию x/5 = 4/10. Найди x.',answer:'2',hint:'Используй основное свойство пропорции.'}),
   'Нахождение процентов от числа':()=>({text:'Найди 20% от 70.',answer:'14',hint:'10% — одна десятая числа.'}),
   'Нахождение числа по процентам':()=>({text:'Число 12 составляет 20% некоторого числа. Найди это число.',answer:'60',hint:'Раздели известную часть на долю в виде десятичной дроби.'}),
   'Задачи на проценты':()=>({text:'Цена 200. Её увеличили на 10%. На сколько увеличилась цена?',answer:'20',hint:'Найди 10% от 200.'}),
   'Положительные и отрицательные числа':()=>({text:'Какое число больше: −3 или −7? Напиши большее.',answer:'-3',hint:'На координатной прямой правее расположено большее число.'}),
   'Модуль числа':()=>({text:'Найди |−8|.',answer:'8',hint:'Модуль — расстояние от нуля.'}),
   'Сложение рациональных чисел':()=>({text:'Вычисли: −5 + 8.',answer:'3',hint:'Представь движение по координатной прямой.'}),
   'Вычитание рациональных чисел':()=>({text:'Вычисли: 4 − 9.',answer:'-5',hint:'Вычитание отрицательно связанного числа можно рассматривать как движение влево.'}),
   'Умножение рациональных чисел':()=>({text:'Вычисли: −6 · 2.',answer:'-12',hint:'При умножении чисел разных знаков результат отрицательный.'}),
   'Деление рациональных чисел':()=>({text:'Вычисли: −18 : 3.',answer:'-6',hint:'При делении чисел разных знаков результат отрицательный.'}),
   'Буквенные выражения':()=>({text:'Найди значение 3a+2 при a=4.',answer:'14',hint:'Подставь значение a и вычисли.'}),
   'Раскрытие скобок':()=>({text:'Раскрой скобки: 3(x+2). Коэффициент при x?',answer:'3',hint:'Умножь 3 на каждый член в скобках.'}),
   'Подобные слагаемые':()=>({text:'Упрости: 4x+3x.',answer:'7x',hint:'Сложи коэффициенты подобных слагаемых.'}),
   'Уравнения':()=>({text:'Реши: x+7=15.',answer:'8',hint:'Убери 7 из обеих частей.'}),
   'Линейные уравнения':()=>({text:'Реши: 5x=35.',answer:'7',hint:'Раздели обе части на 5.'}),
   'Задачи с помощью уравнений':()=>({text:'Задумали число, прибавили 6 и получили 17. Какое число задумали?',answer:'11',hint:'Составь уравнение x+6=17.'}),
   'Координатная плоскость':()=>({text:'Точка A имеет координаты (3;−2). Какова её абсцисса?',answer:'3',hint:'Абсцисса — первая координата.'}),
   'Зависимости и графики':()=>({text:'Если y=2x, чему равен y при x=4?',answer:'8',hint:'Подставь x в формулу.'}),
   'Среднее арифметическое':()=>({text:'Найди среднее арифметическое чисел 6 и 10.',answer:'8',hint:'Сложи числа и раздели на их количество.'}),
   'Средняя скорость':()=>({text:'Путь 150 км пройден за 3 часа. Найди среднюю скорость.',answer:'50',hint:'Скорость = путь ÷ время.'}),
   'Масштаб':()=>({text:'На карте 1 см соответствует 5 км. Сколько км соответствует 4 см?',answer:'20',hint:'Умножь расстояние на масштаб.'}),
   'Окружность и круг':()=>({text:'Как называется отрезок от центра окружности до её точки?',answer:'радиус',hint:'Это основной отрезок окружности от центра.'}),
   'Длина окружности и площадь круга':()=>({text:'Если радиус круга 3 см, какая формула используется для площади?',answer:'pi*r^2',hint:'Площадь круга равна π умножить на квадрат радиуса.'}),
   'Углы':()=>({text:'Чему равен развёрнутый угол в градусах?',answer:'180',hint:'Развёрнутый угол образует прямую.'}),
   'Перпендикулярные прямые':()=>({text:'Какой угол образуют перпендикулярные прямые?',answer:'90',hint:'Перпендикулярность означает прямой угол.'}),
   'Параллельные прямые':()=>({text:'Могут ли две различные параллельные прямые пересекаться? Ответ: да или нет.',answer:'нет',hint:'По определению параллельные прямые в одной плоскости не пересекаются.'}),
   'Треугольники':()=>({text:'Сколько сторон у треугольника?',answer:'3',hint:'Название фигуры подсказывает количество сторон.'}),
   'Четырёхугольники':()=>({text:'Сколько диагоналей у четырёхугольника?',answer:'2',hint:'Соедини противоположные вершины.'}),
   'Прямоугольник и квадрат':()=>({text:'Сторона квадрата 6 см. Найди периметр.',answer:'24',hint:'Периметр квадрата — 4 стороны.'}),
   'Площадь фигур':()=>({text:'Найди площадь прямоугольника 9 см × 4 см.',answer:'36',hint:'S=a·b.'}),
   'Объём и площадь поверхности':()=>({text:'Прямоугольный параллелепипед имеет размеры 2, 3 и 4 см. Найди объём.',answer:'24',hint:'V=a·b·c.'}),
   'Комбинаторика':()=>({text:'Сколько двузначных чисел можно составить из цифр 1 и 2 без повторения?',answer:'2',hint:'Перечисли 12 и 21.'}),
   'Логические задачи':()=>({text:'У Маши 2 яблока, у Кати в 2 раза больше. Сколько у Кати?',answer:'4',hint:'Умножь 2 на 2.'}),
   'Олимпиадные задачи':()=>({text:'Продолжи: 2, 5, 10, 17, 26, …',answer:'37',hint:'Разности увеличиваются на 2.'})
  };
  const f=templates[topic]||templates['Натуральные числа и действия']; return f();
 }
 if(subject==='russian'){
  const map={'Синонимы':['Подбери синоним к слову «смелый».','храбрый'],'Антонимы':['Подбери антоним к слову «высокий».','низкий'],'Части речи':['Определи часть речи слова «быстро».','наречие'],'Словосочетание':['Сколько слов в словосочетании «интересная книга»?','2'],'Грамматическая основа':['Сколько грамматических основ в «Солнце взошло и птицы запели»?','2'],'Пунктуация':['Нужна ли запятая перед «и» в «Солнце взошло и птицы запели»? Ответ: да или нет.','да'],'Имя существительное':['Определи часть речи слова «ученик».','существительное'],'Имя прилагательное':['Определи часть речи слова «зелёный».','прилагательное'],'Глагол':['Определи часть речи слова «бежит».','глагол'],'Имя числительное':['Определи часть речи слова «пять».','числительное'],'Морфемика':['Сколько корней в слове «лесоруб»?','2'],'Предлог':['Является ли «под» предлогом? Ответ: да или нет.','да'],'Союз':['Является ли «и» союзом? Ответ: да или нет.','да'],'Частица':['Является ли «не» частицей в «не знаю»? Ответ: да или нет.','да']};
  const x=map[topic]||['Определи часть речи слова «быстро».','наречие']; return {text:x[0],answer:x[1],hint:'Определи грамматический признак и проверь себя по вопросу или правилу.'};
 }
 if(subject==='english'){
  const map={'Present Simple':['Choose: She ___ to school every day. (go / goes)','goes'],'Present Continuous':['Choose: They ___ now. (play / are playing)','are playing'],'Past Simple':['Choose: He ___ yesterday. (worked / works)','worked'],'There is/There are':['Choose: ___ three books here.','there are'],'Articles a/an/the':['Choose: I have ___ apple. (a / an)','an'],'Comparatives':['Complete: Tom is ___ than Ben. (tall)','taller'],'Superlatives':['Complete: This is the ___ day. (good)','best'],'Can/can’t':['Choose: I ___ swim. (can / cans)','can'],'Must/mustn’t':['Choose: You ___ be polite. (must / musts)','must'],'Should/shouldn’t':['Choose: You ___ study. (should / shoulds)','should'],'Vocabulary: school':['Translate: «книга».','book'],'Vocabulary: family':['Translate: «мама».','mother'],'Vocabulary: hobbies':['Translate: «читать».','read'],'Vocabulary: food':['Translate: «яблоко».','apple'],'Vocabulary: travel':['Translate: «поезд».','train'],'Vocabulary: weather':['Translate: «дождь».','rain'],'Question words':['Choose: ___ is your name? (What / Where)','what'],'Personal pronouns':['Choose: ___ am a student. (I / Me)','i']};
  const x=map[topic]||['Choose: He ___ football every Sunday. (play / plays)','plays']; return {text:x[0],answer:x[1],hint:'Определи время, лицо или значение слова по контексту.'};
 }
 const map={'Units of information':['Сколько битов в одном байте?','8'],'Binary representation':['Сколько цифр используется в двоичной системе?','2'],'Computer networks':['Как называется программа для просмотра сайтов?','браузер'],'Algorithms':['Как называется точная последовательность команд для решения задачи?','алгоритм'],'Logical operations':['Истинно или ложно: И истинно, когда оба условия истинны?','истинно'],'Python output':['Какой командой в Python выводят текст на экран?','print'],'Python variables':['Можно ли записать x=5 в Python? Ответ: да или нет.','да'],'Debugging':['Как называется поиск и исправление ошибок в программе?','отладка'],'Digital safety':['Можно ли сообщать свой пароль незнакомому человеку? Ответ: да или нет.','нет'],'Files and folders':['Где обычно хранятся файлы: в папках или в процессоре?','папках']};
 const x=map[topic]||['Что выполняется по шагам в алгоритме?','команды']; return {text:x[0],answer:x[1],hint:'Вспомни определение термина и проверь его смысл.'};
}
function makeTask(subject,topic,index){const base=BASE_BANK.find(x=>x.subject===subject&&x.topic===topic);if(base)return {...base,id:`${base.id}_${state.completed[subject]}_${index}`};const g=genericTask(subject,topic,index);return{id:`${subject}_${state.completed[subject]}_${index}_${hash(topic)}`,subject,topic,text:g.text,answer:g.answer,hint:g.hint}}
function hash(s){let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))|0;return Math.abs(h)}
function chooseSubjectMenu(){document.getElementById('subjectChooser').hidden=false}
function startSubject(subject){document.getElementById('subjectChooser').hidden=true;lessonPlan={s:subject,title:SUBJECTS[subject],topic:courseTopic(subject,state.completed[subject]+1)};todayTasks=[];const weak=weakTopics(subject).slice(0,2).map(x=>x.topic);const main=lessonPlan.topic;const topics=[...new Set([main,...weak])];for(let i=0;i<10;i++){const topic=topics[i%topics.length];todayTasks.push(makeTask(subject,topic,i))}lessonFinished=false;document.getElementById('dashboard').hidden=true;document.getElementById('lesson').hidden=false;document.getElementById('lessonHeading').textContent=`${SUBJECTS[subject]} · ${main}`;document.getElementById('lessonMeta').textContent=`Урок ${state.completed[subject]+1} из ${LESSONS_PER_SUBJECT} · 10 заданий`;document.getElementById('taskArea').innerHTML=todayTasks.map((t,i)=>`<div class="task" id="task_${t.id}"><h3>${i+1}. ${esc(t.text)}</h3><input id="ans_${t.id}" placeholder="Твой ответ" autocomplete="off"><button onclick="checkTask('${t.id}')">Проверить</button><div id="fb_${t.id}"></div></div>`).join('')+`<div id="finishBox" class="finish"><h2>Когда всё решишь</h2><p id="finishText">Проверь все 10 заданий. После этого станет доступна кнопка завершения.</p><button id="finishBtn" class="primary" onclick="finishLesson()" disabled>Завершить занятие</button></div>`;window.scrollTo({top:0,behavior:'smooth'})}
function checkTask(id){const t=todayTasks.find(x=>x.id===id);if(!t)return;const input=document.getElementById('ans_'+id),raw=input.value,fb=document.getElementById('fb_'+id);if(!raw.trim()){fb.className='feedback bad';fb.innerHTML='<b>Напиши ответ.</b>';return}const ok=normalize(raw)===normalize(t.answer);fb.className='feedback '+(ok?'good':'bad');fb.innerHTML=ok?'<b>Правильно ✅</b>':`<b>Неправильно ❌</b><br><span>${esc(t.hint)}</span>`;state.attempts.push({date:new Date().toISOString(),subject:t.subject,topic:t.topic,ok,lesson:state.completed[t.subject]+1});save();input.disabled=true;document.querySelector('#task_'+id+' button').disabled=true;updateFinishButton()}
function updateFinishButton(){const all=todayTasks.every(t=>document.getElementById('ans_'+t.id)?.disabled);const btn=document.getElementById('finishBtn');if(btn){btn.disabled=!all;btn.textContent=all?'Завершить занятие':'Завершить занятие (сначала проверь все задания)'}if(all)document.getElementById('finishText').textContent='Все 10 заданий проверены. Нажми «Завершить занятие», чтобы засчитать урок.'}
function finishLesson(){if(lessonFinished)return;const all=todayTasks.every(t=>document.getElementById('ans_'+t.id)?.disabled);if(!all)return;lessonFinished=true;const recent=state.attempts.slice(-todayTasks.length),ok=recent.filter(x=>x.ok).length,score=Math.round(ok/todayTasks.length*100),subject=lessonPlan.s;state.completed[subject]=Math.min(LESSONS_PER_SUBJECT,state.completed[subject]+1);state.lessons++;const dk=dateKey();state.lastLesson=dk;if(!state.completedDates.includes(dk))state.completedDates.push(dk);state.streak=calcStreak();state.scores.push({date:new Date().toISOString(),subject:SUBJECTS[subject],title:lessonPlan.title,topic:lessonPlan.topic,score,lesson:state.completed[subject]});save();const nextNo=state.completed[subject]+1;document.getElementById('finishBox').innerHTML=`<h2>Занятие завершено 🎉</h2><p><b>Результат: ${score}%</b></p><p>${SUBJECTS[subject]}: <b>${subjectProgress(subject)}%</b> — урок ${state.completed[subject]} из ${LESSONS_PER_SUBJECT}.</p><div class="next-lesson"><h3>Следующий урок</h3><p>${nextNo<=LESSONS_PER_SUBJECT?`${SUBJECTS[subject]} · ${courseTopic(subject,nextNo)} · урок ${nextNo} из ${LESSONS_PER_SUBJECT}`:'Курс этого предмета завершён на 100%! 🎓'}</p><button class="primary" onclick="showDashboard()">Вернуться в кабинет</button><button class="ghost" onclick="chooseSubjectMenu()">Выбрать другой предмет</button></div>`}
function calcStreak(){const set=new Set(state.completedDates);let d=new Date(),n=0;while(set.has(dateKey(d))){n++;d.setDate(d.getDate()-1)}return n}
function renderDashboard(){document.getElementById('studentName').textContent=STUDENTS[current].name;document.getElementById('tutorTitle').textContent=`Персональный репетитор · ${STUDENTS[current].name}`;document.getElementById('todayStatus').textContent=`Пройдено уроков: ${state.lessons}. Можно выбрать любой предмет.`;document.getElementById('startBtn').textContent='Начать урок';document.getElementById('lessonNo').textContent=`Курсы: ${LESSONS_PER_SUBJECT} уроков по каждому предмету`;
document.getElementById('schedule').innerHTML=SUBJECT_ORDER.map(s=>`<div class="schedule-item"><b>${SUBJECTS[s]}</b><span>${state.completed[s]}/${LESSONS_PER_SUBJECT} уроков</span></div>`).join('');
document.getElementById('progress').innerHTML=SUBJECT_ORDER.map(k=>{const v=subjectProgress(k);return `<div class="bar"><div class="bar-top"><span>${SUBJECTS[k]}</span><b>${v}%</b></div><div class="track"><div class="fill" style="width:${v}%"></div></div><small>${state.completed[k]} из ${LESSONS_PER_SUBJECT} уроков</small></div>`}).join('');
const weak=weakTopics();document.getElementById('errors').innerHTML=weak.length?weak.slice(0,8).map(x=>`<li>${esc(x.topic)} — ${Math.round(x.ok/x.n*100)}% правильных</li>`).join(''):'<li>Пока собираем данные.</li>';const strengths=Object.values(topicStats()).filter(x=>x.ok>0).sort((a,b)=>(b.ok/b.n)-(a.ok/a.n));document.getElementById('strengths').innerHTML=strengths.length?strengths.slice(0,8).map(x=>`<li>${esc(x.topic)} — ${Math.round(x.ok/x.n*100)}% правильных</li>`).join(''):'<li>Пока собираем данные.</li>';document.getElementById('scores').innerHTML=state.scores.length?`<table><tr><th>Дата</th><th>Предмет</th><th>Урок</th><th>Результат</th></tr>${state.scores.slice(-20).reverse().map(x=>`<tr><td>${new Date(x.date).toLocaleDateString('ru-RU')}</td><td>${esc(x.subject)}</td><td>${esc(x.topic||x.title)}</td><td><b>${x.score}%</b></td></tr>`).join('')}</table>`:'<p>Оценок пока нет.</p>'}
function showDashboard(){document.getElementById('login').hidden=true;document.getElementById('lesson').hidden=true;document.getElementById('dashboard').hidden=false;document.getElementById('subjectChooser').hidden=true;renderDashboard()}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function restore(){const id=sessionStorage.getItem('tutor_session');if(id&&STUDENTS[id]){current=id;state=load(id);showDashboard()}}
restore();
